Update index.html
Fixed error cause my resolving merge request.

ERROR: when linking Materialize.css this causes the text within the file to become white.

Solution: Change classes within HTML from bootstrap format into materialize. (translate bootstrap into materiallize)